version: '3'
services:
  knowledge_repo:
    image: "intuitionmachine/knowledge_repo"
    ports:
      - "7000:7000"
    volumes:
      - "./knowledge-repo/project_repo:/root/workspace/project_repo"
    command: knowledge_repo --repo /root/workspace/project_repo runserver 
  tensorflow:
    image: "rocm/tensorflow:rocm2.9-ub18.04-tf1.15-python3"
    ports:
      - "8888:8888"
    volumes:
      - "./SEEDBank:/root/work"
      - "~/dockerx:/dockerx"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    cap_add:
      - SYS_PTRACE
    network_mode: "host"
    security_opt:
      - seccomp=unconfined
    command: jupyter notebook --NotebookApp.token='' --allow-root

